#!/usr/bin/env bash
set -eou pipefail

unpackedTo="$1" || {
  printf 'usage: SYSBACKUP_UNPACKED_DIR
         eg: /usr/local/sysbackup
  ' >&2
  exit 1
}

set -x

systemctl daemon-reload

mkdir -vp /etc/systemd/system/sysbackup.service.d/
ln -sv "$unpackedTo"/sysbackup.conf \
         /etc/systemd/system/sysbackup.service.d/
mkdir -p /usr/lib/systemd/system/
for unit in "$unpackedTo"/sysbackup.{service,timer}; do
  ln -sv "$unit" /usr/lib/systemd/system/
done

systemctl daemon-reload
# WARNING: timer MUST come first; somehow systemd gets confused otherwise
systemctl enable sysbackup.{timer,service}
systemctl show sysbackup.service | grep Environment
systemctl start sysbackup.service
