= sysrestic: encapsulate restic & your laptop
:LVMencryption: https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system
:slocRefBin: https://github.com/jzacsh/bin/blob
:homeScript: {slocRefBin}/b73710888c23d/share/resticw.sh
:systemScript: {slocRefBin}/b73710888c23d/share/borgw_system.sh
:golangforkat: 4031a8c162765b
:resticurl: https://restic.github.io
:whatisrepo: https://restic.readthedocs.io/en/stable/#quick-start
:excludes: https://restic.readthedocs.io/en/stable/manual.html?highlight=exclude

Facilitates system-wide backup for an encrypted drive on a personal computer,
using {resticurl}[`restic`].

== Motivation

This project provides two things for my personal use footnoteref:[usecase, I
assume `/` is {LVMencryption}[encrypted somehow] and I just want local-only
backups for my sanity but not for production robustness]:

1. Debian *package*: a `.deb` for me to `dpkg -i` and forget about
2. `sysrestic` *exclude-files* logic: a local binary to aggregate some ASCII
    {excludes}[excludes] files for me, in a semi-predictable way

== Installing & Updating

Everything below assumes you:

a. know what the `restic` {resticurl}[backup program] is; go check it out!
b. are on Debian...ish
c. have a `restic` {whatisrepo}[repo] somewhere on local disk +
  _(or plan to `restic init` one soon...)_


.clean slate; skip if no git repo
----
$ git clone github.com/jzacsh/sysrestic && cd sysrestic/
$ git archive --output /tmp/sysrestic.tgz master --prefix sysrestic/
$ cd /tmp/ && tar -xf sysrestic.tgz && cd sysrestic
----

.build
----
$ make deb
go build ./...
go build -o sysrestic
sudo --remove-timestamp
mkdir -p sysrestic_0.1/usr/lib/sysrestic/bin
mkdir -p sysrestic_0.1/usr/lib/sysrestic/systemd
mkdir -p sysrestic_0.1/etc/
mkdir -p sysrestic_0.1/DEBIAN
mkdir -p sysrestic_0.1/usr/lib/systemd/system/
mkdir -p sysrestic_0.1/etc/systemd/system/sysrestic.service.d
cp sysrestic sysrestic_0.1/usr/lib/sysrestic/bin/
cp debian/system.exclude sysrestic_0.1/usr/lib/sysrestic/default.exclude
cp debian/system.exclude sysrestic_0.1/etc/sysrestic.exclude
cp debian/systemd.conf   sysrestic_0.1/etc/systemd/system/sysrestic.service.d/systemd.conf
cp debian/systemd.conf   sysrestic_0.1/usr/lib/sysrestic/systemd/example.conf
cp debian/sysrestic.service sysrestic_0.1/usr/lib/sysrestic/systemd/sysrestic.service
cp debian/sysrestic.timer   sysrestic_0.1/usr/lib/sysrestic/systemd/sysrestic.timer
cd sysrestic_0.1/usr/lib/systemd/system/ && ln -s /usr/lib/sysrestic/systemd/sysrestic.service
cd sysrestic_0.1/usr/lib/systemd/system/ && ln -s /usr/lib/sysrestic/systemd/sysrestic.timer
echo /etc/sysrestic.exclude >> sysrestic_0.1/DEBIAN/conffiles
echo /etc/systemd/system/sysrestic.service.d/systemd.conf >> sysrestic_0.1/DEBIAN/conffiles
chmod 600 sysrestic_0.1/etc/systemd/system/sysrestic.service.d/systemd.conf
cp debian/control sysrestic_0.1/DEBIAN/
sed --in-place "s/VERSION_HERE/0.1/g" sysrestic_0.1/DEBIAN/control
sudo chown -R root:root sysrestic_0.1
[sudo] password for jzacsh:
sudo fakeroot dpkg-deb --build sysrestic_0.1
dpkg-deb: building package 'sysrestic' in 'sysrestic_0.1.deb'.
success; now consider `sudo` removing sysrestic_0.1
----

.install
----
$ sudo rm sysrestic_0.1/ -rf # <1>
$ sudo dpkg -i sysrestic_0.1.deb # <2>
----
<1> don't forget to cleanup my `root` mess
<2> *this* is the actual install

.if you're curious
----
$ find /usr/lib/sysrestic/ \
  /etc/sysrestic* \
  /usr/lib/systemd/system/sysrestic* \
  /etc/systemd/system/sysrestic* -exec file {} +;
----

.configure: set `$SYSRESTIC_REPO` & `$RESTIC_PASSWORD`
----
$ $EDITOR /etc/systemd/system/sysrestic.service.d/systemd.conf
$ $EDITOR /etc/sysrestic.exclude # <1>
----
<1> optional

.systemd: tell your machine
----
$ systemctl daemon-reload
$ systemctl enable sysrestic.{timer,service} # <1>
$ systemctl start sysrestic.timer
$ systemctl status sysrestic.{timer,service}
----
<2> here & below are vanilla commands; part of regular usage

=== Usage

Systemd -- ie: `Systemctl` -- is now your interface for this repository's
impact on your machine.

.modify frequency of backups
----
$ $EDITOR /etc/systemd/system/sysrestic.timer
----

.check latest status
----
$ systemctl status sysrestic.{timer,service}
----

.watch logs
----
$ journalctl --pager-end --follow sysrestic.service
----

.control backups
----
$ systemctl stop sysrestic.service
$ systemctl restart sysrestic.service
----

.disable upcoming backups
----
$ systemctl disable sysrestic.timer
----

.update if you've moved your `restic` repo
----
$ $EDITOR /etc/systemd/system/sysrestic.service.d/systemd.conf # <1>
----
<1> specifically, change the `$SYSRESTIC_REPO` value

== Contributing

Despite remarks above, that this serves a highly personal use to my own laptop,
I'd be *happy* to patch or accept patches to make this useful for you too! If
you want a quick overview on *what* is installed, this README as of
`{golangforkat}` walked through *exactly* what I tried to encode into the
debian package.

=== `sysrestic` command

Most of this repo deals with the small `sysrestic` tool. Debian packaging is
only addressed by `./debian/` and its contents, and the make target `deb` & co.

.build & test: `sysrestic`, `test`
----
$ make sysrestic test
go build ./...
go build -o sysrestic
go test ./...
ok  	github.com/jzacsh/sysrestic	0.008s
ok  	github.com/jzacsh/sysrestic/exclude	0.025s
ok  	github.com/jzacsh/sysrestic/file	0.021s
ok  	github.com/jzacsh/sysrestic/usr	0.016s
----

.make `all`: `clean`, `test`, `sysrestic`
----
$ make clean
rm -f -rf sysrestic sysrestic_*

# snipped ... same as above
----

NOTE: until `{golangforkat}`, this project was originally a documentation effort
so I would understand what/how my backup script was installed when I'd
inevitably forget 6 months down the line. Now this is a locally-built debian
package that is hopefully just as self-documentation, thanks to tools like `dpkg
-S ...` and `dpkg-query`, `apt remove`, etc.
