#!/usr/bin/env bash
set -euo pipefail

lgCln() ( set +x; printf 'cleaning up %s\n' "$@"; )

printf 'disabling systemd service\n'
systemctl disable sybackup.{timer,service}

lgCln 'systemd override config'
rm /etc/systemd/system/sysbackup.d/ -rf

lgCln 'systemd files'
rm /usr/lib/systemd/sysbackup* -v

printf 'WARNING: run the below to finish up:
  rm /usr/local/sysbackup/ -rf
'
